# Generated by Django 4.2.8 on 2024-11-25 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recommendationresult",
            name="explanation",
        ),
        migrations.RemoveField(
            model_name="recommendationresult",
            name="fin_prdt_cd",
        ),
        migrations.AddField(
            model_name="recommendationresult",
            name="deposit_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.depositproduct",
            ),
        ),
        migrations.AddField(
            model_name="recommendationresult",
            name="saving_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.savingproduct",
            ),
        ),
        migrations.AddField(
            model_name="recommendationresult",
            name="scores",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recommendationresult",
            name="product_type",
            field=models.CharField(max_length=10),
        ),
    ]
