# Generated by Django 4.2.8 on 2024-11-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
