# Generated by Django 4.2.8 on 2024-11-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['currency_code', 'date'], name='exchange_ex_currenc_17df77_idx')],
                'unique_together': {('currency_code', 'date')},
            },
        ),
    ]
